name: Comprehensive Web Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Full Web Deployment Diagnostics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /var/www/html # Deploy directly to the web root
      
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update all packages
            sudo dnf update -y

            # Install Apache if not already installed
            sudo dnf install -y httpd

            # Ensure the web directory exists
            sudo mkdir -p /var/www/html

            # Set correct permissions
            sudo chown -R apache:apache /var/www/html
            sudo chmod -R 755 /var/www/html

            # Ensure FirewallD is installed and running
            sudo dnf install -y firewalld
            sudo systemctl start firewalld
            sudo systemctl enable firewalld

            # Open necessary ports
            sudo firewall-cmd --permanent --add-service=http
            sudo firewall-cmd --permanent --add-service=https
            sudo firewall-cmd --permanent --add-port=443/tcp
            sudo firewall-cmd --reload

            # Ensure Apache starts on boot
            sudo systemctl enable --now httpd

            # SELinux adjustments (optional but recommended)
            sudo restorecon -R /var/www/html
            sudo setsebool -P httpd_can_network_connect on

            # Display diagnostic information
            echo "=== Web Server Status ==="
            sudo systemctl status httpd || true
            
            echo "=== Firewall Status ==="
            sudo systemctl status firewalld || true
            
            echo "=== Firewall Rules ==="
            sudo firewall-cmd --list-all || true
            
            echo "=== SELinux Status ==="
            getenforce
