name: Comprehensive Web Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Full Web Deployment Diagnostics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Validate SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pre-flight checks
            echo "Performing pre-deployment checks..."
            
            # Check disk space
            df -h
            
            # Verify user permissions
            whoami
            id
      
      - name: Prepare Target Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Robust directory preparation
            set -e  # Exit immediately if a command exits with a non-zero status
            
            # Create directories with explicit permissions
            sudo mkdir -p /var/www/html
            
            # Determine the correct web server group
            WEB_GROUP=$(grep -E '^apache:|^www-data:' /etc/group | cut -d: -f1)
            
            # If no web group found, default to current user's group
            WEB_GROUP=${WEB_GROUP:-${{ secrets.USERNAME }}}
            
            # Set ownership and permissions
            sudo chown -R ${{ secrets.USERNAME }}:$WEB_GROUP /var/www/html
            sudo chmod -R 755 /var/www/html
            
            # Verify directory setup
            echo "Web Group: $WEB_GROUP"
            ls -ld /var/www/html
            
            # Log directory preparation
            echo "Target directory prepared successfully"
      
      - name: Deploy Web Files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /var/www/html
          EXCLUDE: |
            .git
            .github
            .gitignore
            README.md
      
      - name: Configure Web Server and Security
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Comprehensive server configuration
            set -e
            
            # Determine the correct web server group
            WEB_GROUP=$(grep -E '^apache:|^www-data:' /etc/group | cut -d: -f1)
            
            # If no web group found, default to current user's group
            WEB_GROUP=${WEB_GROUP:-${{ secrets.USERNAME }}}
            
            # Update system packages
            sudo yum update -y
            
            # Install and configure web server
            sudo yum install -y httpd mod_ssl
            
            # Set correct permissions
            sudo chown -R apache:$WEB_GROUP /var/www/html
            sudo chmod -R 750 /var/www/html  # More restrictive permission
            
            # Configure firewall
            sudo systemctl start firewalld
            sudo systemctl enable firewalld
            
            # Open necessary ports with permanent configuration
            sudo firewall-cmd --permanent --add-service=http
            sudo firewall-cmd --permanent --add-service=https
            sudo firewall-cmd --permanent --add-port=443/tcp
            sudo firewall-cmd --reload
            
            # Configure SELinux
            sudo setsebool -P httpd_can_network_connect on
            sudo restorecon -R /var/www/html
            
            # Start and enable Apache
            sudo systemctl restart httpd
            sudo systemctl enable httpd
            
            # Detailed diagnostics
            echo "=== System Deployment Report ==="
            echo "Date: $(date)"
            echo ""
            echo "--- Web Server Status ---"
            sudo systemctl status httpd || true
            
            echo ""
            echo "--- Firewall Configuration ---"
            sudo firewall-cmd --list-all || true
            
            echo ""
            echo "--- SELinux Status ---"
            getenforce
            
            echo ""
            echo "--- Directory Permissions ---"
            ls -ld /var/www/html
            ls -l /var/www/html
      
      - name: Verify Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Comprehensive deployment verification
            
            # Check web server response
            curl -I http://localhost || echo "Web server not responding"
            
            # Verify file deployment
            if [ "$(ls -A /var/www/html)" ]; then
                echo "Files successfully deployed"
            else
                echo "ERROR: No files found in deployment directory"
                exit 1
            fi
