name: Comprehensive Web Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Full Web Deployment Diagnostics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Comprehensive Web Server Setup
            sudo dnf update -y
            
            # Install and configure web server
            sudo dnf install -y httpd
            
            # Ensure web directory exists
            sudo mkdir -p /var/www/html
            
            # Move files to web directory
            sudo cp -R /home/${{ secrets.USERNAME }}/* /var/www/html/
            
            # Set correct permissions
            sudo chown -R apache:apache /var/www/html
            sudo chmod -R 755 /var/www/html
            
            # Configure firewall
            sudo firewall-cmd --permanent --add-service=http
            sudo firewall-cmd --permanent --add-service=https
            sudo firewall-cmd --reload
            
            # SELinux configurations
            sudo restorecon -R /var/www/html
            
            # Restart web server
            sudo systemctl restart httpd
            sudo systemctl enable httpd
            
            # Diagnostic information
            echo "Web Server Status:"
            sudo systemctl status httpd
            
            echo "Directory Contents:"
            ls -la /var/www/html
            
            echo "Firewall Rules:"
            sudo firewall-cmd --list-all
            
            echo "SELinux Status:"
            getenforce
