name: Simple Logger

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, this is a scheduled job!"
