name: Scheduled Time Logger

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  log-time:
    runs-on: ubuntu-latest
    steps:
      - name: Get current server time
        shell: bash
        run: echo "Current Time: $(date)"
